<?xml version="1.0"?>
<package format="3">
  <name>signal_pipeline</name>
  <version>0.0.1</version>
  <description>Minimal sine->RMS pipeline for November</description>
  <maintainer email="ram@example.com">Ram</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
</package>
